CREATE DATABASE clinic_database;

CREATE DATABASE

\c clinic_database

CREATE TABLE medical_histories(
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
admitted_at TIMESTAMP,
patient_id INT,
status VARCHAR(30)
);

CREATE TABLE patients(
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name VARCHAR(30),
date_of_birth DATE
);

CREATE TABLE

ALTER TABLE medical_histories
ADD CONSTRAINT patient_id FOREIGN KEY(patient_id) REFERENCES patients(id);

ALTER TABLE

CREATE TABLE treatments(
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
type VARCHAR(30),
name VARCHAR(30)
);

CREATE TABLE